apiVersion: v1
kind: Template
labels:
    template: apache-php7-mariadb-template
metadata:
  name: apache-php7-mariadb-ephemeral
  annotations:
    description: "Apache 2.4 with PHP 7, MariaDB and phpMyAdmin"
    iconClass: "icon-php"
    tags: "quickstart,php,database"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Apache 2.4
    name: ${APP_SERVICE_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_SERVICE_NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying Apache
    labels:
      service: apache-2.4
    name: ${APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_SERVICE_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${APP_SERVICE_NAME}
          service: apache-2.4
        name: ${APP_SERVICE_NAME}
      spec:
        containers:
        - env:
          image: 1and1internet/ubuntu-16-apache-2.4-php-7.0:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
                port: 8080
            timeoutSeconds: 1
          name: ${APP_SERVICE_NAME}
          volumeMounts:
          - mountPath: /var/www/html
            name: apache-data
        restartPolicy: Always
        securityContext:
          runAsUser: ${OPENSHIFT_USER}
        volumes:
        - emptyDir:
            medium: ""
          name: apache-data
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: MariaDB and phpMyAdmin
    creationTimestamp: null
    name: ${DATABASE_SERVICE_NAME}
  spec:
    portalIP: ""
    ports:
    - name: mariadb
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
    selector:
      name: ${DATABASE_APP_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${DATABASE_SERVICE_NAME}
  spec:
    host: ${DATABASE_ADMIN_DOMAIN}
    to:
      kind: Service
      name: ${DATABASE_SERVICE_NAME}
    port:
      targetPort: 8080
      protocol: TCP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying MariaDB
    labels:
      service: mariadb-10.0
    name: ${DATABASE_APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_APP_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_APP_SERVICE_NAME}
          service: mariadb-10.0
        name: ${DATABASE_APP_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_ROOT_PASSWORD}
          image: 1and1internet/ubuntu-16-nginx-1.10.0-php-7.0-phpmyadmin-4.6-mariadb-10.0:latest
          imagePullPolicy: Always
          name: ${APP_SERVICE_NAME}
        resources:
          limits:
            memory: ${MEMORY_LIMIT}
        securityContext:
          runAsUser: ${OPENSHIFT_USER}
        volumes:
        - emptyDir:
            medium: ""
          name: ${DATABASE_SERVICE_NAME}-data
    triggers:
    - type: ConfigChange
parameters:
- description: Application service name
  displayName: Application service name
  name: APP_SERVICE_NAME
  required: true
  from: apache-[a-z]{5}
  generate: expression
- description: The exposed hostname that will route to the Apache Server, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: Database application service name
  displayName: Database application service name
  from: mysql-[0-9]{5}
  generate: expression
  name: DATABASE_APP_SERVICE_NAME
  required: true
- description: MariaDB Username
  displayName: Username for MariaDB
  from: user[A-Z0-9]{4}
  generate: expression
  name: MYSQL_USER
  required: true
- description: MariaDB Password
  displayName: Password for MariaDB
  from: '[a-zA-Z0-9]{10}'
  generate: expression
  name: MYSQL_PASSWORD
  required: true
- description: MariaDB Root Password
  displayName: Password for MariaDB Root/Administrator User
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_ROOT_PASSWORD
  required: true
- description: Service Name for MariaDB
  displayName: Service Name for MariaDB
  name: DATABASE_SERVICE_NAME
  required: true
  value: mysql
- description: Database Admin URL
  displayname: Database Admin URL
  name: DATABASE_ADMIN_DOMAIN
  required: true
- description: Openshift User
  displayname: Openshift User
  name: OPENSHIFT_USER
  required: true
