apiVersion: v1
kind: Template
labels:
    template: apache-php7-mysql-template
metadata:
  name: apache-php7-mysql-ephemeral
  annotations:
    description: "Apache 2.4 with PHP 7 and MySQL"
    iconClass: "icon-php"
    tags: "apache,php,php7,mysql"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Apache 2.4
    name: ${APP_SERVICE_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_SERVICE_NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying Apache
    labels:
      service: apache-2.4
    name: ${APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_SERVICE_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${APP_SERVICE_NAME}
          service: apache-2.4
        name: ${APP_SERVICE_NAME}
      spec:
        containers:
        - env:
          image: 1and1internet/ubuntu-16-apache-2.4-php-7.0:unstable
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
                port: 8080
            timeoutSeconds: 1
          name: ${APP_SERVICE_NAME}
          volumeMounts:
          - mountPath: /var/www
            name: apache-data
        restartPolicy: Always
        securityContext:
          runAsUser: 1021400030
        volumes:
        - emptyDir:
            medium: ""
          name: apache-data
    triggers:
    - type: ConfigChange
parameters:
- description: Size of Storage
  displayName: Web directory size
  name: VOLUME_CAPACITY
  required: true
  value: 5Gi
- description: Application service name
  displayName: Application service name
  name: APP_SERVICE_NAME
  required: true
  from: apache-[a-z]{5}
  generate: expression
- description: The exposed hostname that will route to the Apache Server, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
